secret:
  serviceKey: ${serviceKey}

spring:
  profiles:
    active: local
    group:
      development:
        - local
      production:
        - prod

---

spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/Round-Weather-Backend-DB
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database: h2
    show-sql: true